### ISSUE TITLE
Some of the assets such as images are not available.

### ISSUE THREAD

**Issue by Kinshu-Learner** [Oct-o-Dev/gwoc-idk#13]
Some of the assets such as images are not available, which won't allow people to easily fork and work with the repository locally.
![image](https://github.com/user-attachments/assets/14febc30-c3b0-4d7a-9ab2-49cacf9efe37)
Please fix these issues first, so that people can easily work with the repository locally and can thus contribute without much hassle.

**Comment by ZEviod** [comment]
Yes I know, currently it is in re-setup of gwoc 
Once it is enabled properly it is greatly available to contribute for others
